pretrained_model_name_or_path: 'lambdalabs/sd-image-variations-diffusers'
# modify the unet path; use the stage 1 checkpoint
# pretrained_unet_path: '/home/xuyimeng/Repo/Wonder3D/outputs/splatter/wonder3D-mix-128-lara-splatter-lmdb-4gpus/checkpoint-run5-13500'
# pretrained_unet_path: 'outputs/splatter/wonder3D-joint-128-lara_splatter-rope-ZERO_SNR-BSZ16_acc1_gpu4-all_trainable/checkpoint-20k'
# pretrained_unet_path: /home/xuyimeng/Repo/Wonder3D/outputs/splatter/2DGS_LVIS/wonder3D-mix-128-LVIS-splatter-8gpus-bsz64/checkpoint
pretrained_unet_path: /home/xuyimeng/Repo/Wonder3D/outputs/splatter/2DGS_LVIS/wonder3D-stage2-joint_mid_only-LVIS-splatter-8gpus-bsz64/unet-8000
# pretrained_decoder_path: /home/chenwang/Repo/LGM/runs/finetune_decoder/workspace_train_sep/00001-LVIS-independent_encode_mv-resume_00012-numV12-loss_render1.5_splatter1.0_lpips2.0-lr5e-06-Plat5/eval_global_step_2000_ckpt/model.safetensors
pretrained_decoder_path: /home/chenwang/Repo/LGM/runs/finetune_decoder/workspace_train_sep/00002-LVIS-independent_encode_mv-resume_00012-numV12-loss_render1.5_splatter1.0_lpips2.0-lr5e-06-Plat5/eval_global_step_2000_ckpt/model.safetensors
revision: null
rendering_loss_2dgs: true
train_dataset:
  root_dir: '/mnt/kostas-graid/datasets/xuyimeng/GobjLara/dataset/gobjaverse/gobjaverse.h5'  # change to your path
  object_list: './data_lists/single_obj.json'
  invalid_list: './data_lists/lvis_invalid_uids_nineviews.json'
  num_views: 6
  groups_num: 1
  bg_color: 'three_choices'
  # img_wh: [256, 256]
  img_wh: [128, 128] # fast dev
  validation: false
  num_validation_samples: 4
  read_normal: true
  read_color: true
  overfit: false
  debug: false
  lmdb_6view_base: '/mnt/kostas-graid/datasets/xuyimeng/lara/lmdb_database_1views_whole_HASHED/lmdb_database'
  rendering_loss_2dgs: false  #${rendering_loss_2dgs} 
  read_first_view_only: true
  render_views: 10
  dataset_type: 'lvis'
  splatter_mode: "2dgs"
  render_size: 512
validation_dataset:
  root_dir: ${train_dataset.root_dir}  # change to your path
  object_list: './data_lists/single_obj.json'
  invalid_list: './data_lists/lvis_invalid_uids_nineviews.json'
  num_views: 6
  groups_num: 1
  bg_color: 'white'
  img_wh: ${train_dataset.img_wh}
  validation: true
  num_validation_samples: 4
  read_normal: true
  read_color: true
  overfit: ${train_dataset.overfit}
  debug: ${train_dataset.debug}
  lmdb_6view_base: ${train_dataset.lmdb_6view_base}
  rendering_loss_2dgs: ${rendering_loss_2dgs} 
  read_first_view_only: false # ${train_dataset.read_first_view_only}
  render_views: 20 # ${train_dataset.render_views}
  dataset_type: ${train_dataset.dataset_type}
  splatter_mode: ${train_dataset.splatter_mode}
  render_size: ${train_dataset.render_size}
validation_train_dataset:
  root_dir: ${train_dataset.root_dir}  # change to your path
  object_list: './data_lists/single_obj.json'
  invalid_list: './data_lists/lvis_invalid_uids_nineviews.json'
  num_views: 6
  groups_num: 1
  bg_color: 'three_choices'
  img_wh: ${train_dataset.img_wh}
  validation: false
  num_validation_samples: 4 # 32
  num_samples: 32
  read_normal: true
  read_color: true
  overfit: ${train_dataset.overfit}
  debug: ${train_dataset.debug}
  lmdb_6view_base: ${train_dataset.lmdb_6view_base}
  rendering_loss_2dgs: ${rendering_loss_2dgs} 
  read_first_view_only: false # ${train_dataset.read_first_view_only}
  render_views: ${train_dataset.render_views}
  dataset_type: ${train_dataset.dataset_type}
  splatter_mode: ${train_dataset.splatter_mode}
  render_size: ${train_dataset.render_size}

output_dir:  outputs/splatter/2DGS_LVIS/wonder3D-stage2-All_trainable-LVIS-splatter-8gpus-bsz64

seed: 42
train_batch_size: 8 # original paper uses 32
validation_batch_size: 2 # use 1 for gassian reconstruction ${train_batch_size} # 16
validation_train_batch_size: 16
max_train_steps: 20000
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 5.e-5
scale_lr: false
lr_scheduler: "constant_with_warmup"
lr_warmup_steps: 100
snr_gamma: 5.0
use_8bit_adam: false
allow_tf32: true
use_ema: true  
dataloader_num_workers: 8 # 64
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.e-2
adam_epsilon: 1.e-08
max_grad_norm: 1.0
prediction_type: null
vis_dir: vis
logging_dir: logs
mixed_precision: "fp16"
report_to: 'tensorboard'
local_rank: -1
checkpointing_steps: 2000
checkpoints_total_limit: null
last_global_step: 0

# resume_from_checkpoint: /home/xuyimeng/Repo/Wonder3D/outputs/splatter/wonder3D-joint-128-lara_splatter-ROPE_domainXY_ids-BSZ16_acc2_gpu2-all_trainable/checkpoint-run2
resume_from_checkpoint: latest
enable_xformers_memory_efficient_attention: true
validation_steps: 1000
validation_sanity_check: true
tracker_project_name: 'mvdiffusion-image-v1'

trainable_modules: null
# trainable_modules: ['joint_mid']
use_classifier_free_guidance: true
condition_drop_rate: 0.05
drop_type: 'drop_as_a_whole'  # modify
camera_embedding_lr_mult: 10.
scale_input_latents: true

pipe_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  num_views: 6

validation_guidance_scales: [1., 3., 5., 7., 9.]
pipe_validation_kwargs:
  eta: 1.0
validation_grid_nrow: 10

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  projection_class_embeddings_input_dim: 16  # modify: 10 for 2 domains
  num_views: 6
  sample_size: 16 # when im_hw=128
  zero_init_conv_in: false
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: true
  multiview_attention: true
  sparse_mv_attention: false
  mvcd_attention: false
  low_cpu_mem_usage: false # added to load ckpt 

num_views: 6
camera_embedding_type: 'e_de_da_sincos'
zero_terminal_snr: true
sync_domain_timesteps: true

