pretrained_model_name_or_path: lambdalabs/sd-image-variations-diffusers
pretrained_unet_path: /home/xuyimeng/Repo/Wonder3D/outputs/splatter/wonder3D-joint-128-lara_splatter-rope-ZERO_SNR-BSZ16_acc1_gpu4-all_trainable/first-20k/checkpoint-20k
pretrained_decoder_path: /mnt/kostas_home/lilym/LGM/LGM/runs/finetune_decoder/workspace_train_sep/00012-independent_encode_mv_True-no_resume-GTnormal_loss_after6000-BSZ16-numV15-loss_render1.0_splatter1.0_lpips2.0-lr5e-06-Plat5/eval_global_step_29000_ckpt/model.safetensors
revision: null
train_dataset:
  root_dir: /mnt/kostas-graid/datasets/xuyimeng/GobjLara/dataset/gobjaverse/gobjaverse.h5
  object_list: ./data_lists/single_obj.json
  invalid_list: ./data_lists/lvis_invalid_uids_nineviews.json
  num_views: 6
  groups_num: 1
  bg_color: three_choices
  img_wh:
  - 128
  - 128
  validation: false
  num_validation_samples: 4
  read_normal: true
  read_color: true
  overfit: false
  debug: false
  lmdb_6view_base: null
  rendering_loss_2dgs: false
  read_first_view_only: true
  render_views: 10
  dataset_type: lara
  normalize_campose: false
  render_size: 256
validation_dataset:
  root_dir: ${train_dataset.root_dir}
  # root_dir: /mnt/kostas-graid/sw/envs/chenwang/data/gso/gso_recon_gsec512
  object_list: ./data_lists/single_obj.json
  invalid_list: ./data_lists/lvis_invalid_uids_nineviews.json
  num_views: 6
  groups_num: 1
  bg_color: white
  img_wh: ${train_dataset.img_wh}
  validation: true
  num_validation_samples: 4
  read_normal: true
  read_color: true
  overfit: ${train_dataset.overfit}
  debug: ${train_dataset.debug}
  lmdb_6view_base: ${train_dataset.lmdb_6view_base}
  rendering_loss_2dgs: ${rendering_loss_2dgs}
  read_first_view_only: false
  render_views: 20
  dataset_type: lara
  normalize_campose: ${train_dataset.normalize_campose}
  render_size: ${train_dataset.render_size}
validation_train_dataset:
  root_dir: ${train_dataset.root_dir}
  object_list: ./data_lists/single_obj.json
  invalid_list: ./data_lists/lvis_invalid_uids_nineviews.json
  num_views: 6
  groups_num: 1
  bg_color: white
  img_wh: ${train_dataset.img_wh}
  validation: true
  num_validation_samples: 4
  read_normal: true
  read_color: true
  overfit: ${train_dataset.overfit}
  debug: ${train_dataset.debug}
  lmdb_6view_base: ${train_dataset.lmdb_6view_base}
  rendering_loss_2dgs: ${rendering_loss_2dgs}
  read_first_view_only: false
  render_views: 20
  dataset_type: ${train_dataset.dataset_type}
  normalize_campose: ${train_dataset.normalize_campose}
  render_size: ${train_dataset.render_size}
  
output_dir: outputs/splatter/wonder3D-joint-128-lara_splatter-rope-all_trainable
fovy: 39.6

seed: 42
train_batch_size: 64
validation_batch_size: 8
validation_train_batch_size: 8
max_train_steps: 20000
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 5.0e-05
scale_lr: false
lr_scheduler: constant_with_warmup
lr_warmup_steps: 100
snr_gamma: 5.0
use_8bit_adam: false
allow_tf32: true
use_ema: true
dataloader_num_workers: 8
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
prediction_type: null
logging_dir: logs
vis_dir: vis
mixed_precision: fp16
report_to: tensorboard
local_rank: -1
checkpointing_steps: 2000
checkpoints_total_limit: null
resume_from_checkpoint: latest
enable_xformers_memory_efficient_attention: true
validation_steps: 2000
validation_sanity_check: true
tracker_project_name: mvdiffusion-image-v1
trainable_modules: null
use_classifier_free_guidance: true
condition_drop_rate: 0.05
scale_input_latents: true
pipe_kwargs:
  camera_embedding_type: e_de_da_sincos
  num_views: 6
pipe_validation_kwargs:
  eta: 1.0
unet_from_pretrained_kwargs:
  camera_embedding_type: e_de_da_sincos
  projection_class_embeddings_input_dim: 16
  num_views: 6
  sample_size: 16
  zero_init_conv_in: false
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: true
  multiview_attention: true
  sparse_mv_attention: false
  mvcd_attention: false
  low_cpu_mem_usage: false
validation_guidance_scales:
- 1.0
- 3.0
- 5.0
validation_grid_nrow: 10
camera_embedding_lr_mult: 10.0
num_views: 6
camera_embedding_type: e_de_da_sincos
drop_type: drop_as_a_whole
last_global_step: 0
rendering_loss_2dgs: true
zero_terminal_snr: true
sync_domain_timesteps: true